# Generated by Django 3.2 on 2022-02-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0003_rename_product_type_bar_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='barbary_api.account'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='owner_bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barbary_api.account'),
        ),
    ]
