# Generated by Django 3.2 on 2022-02-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0006_alter_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
