# Generated by Django 3.2 on 2022-02-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0007_alter_bar_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='description',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
