# Generated by Django 3.2 on 2022-02-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0008_alter_bar_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='isSpecial',
            field=models.BooleanField(default=False),
        ),
    ]
