# Generated by Django 3.2 on 2022-02-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0009_bar_isspecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='position',
            field=models.CharField(blank=True, choices=[('driver', 'driver'), ('manager', 'manager')], max_length=7, null=True),
        ),
    ]
