# Generated by Django 3.2 on 2022-02-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0010_account_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='isTopShow',
            field=models.BooleanField(default=False),
        ),
    ]
