# Generated by Django 3.2 on 2022-02-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0011_bar_istopshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.CharField(blank=True, choices=[('driver', 'driver'), ('manager', 'manager'), ('company', 'company')], max_length=7, null=True),
        ),
    ]
