# Generated by Django 3.2 on 2022-02-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0012_alter_account_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='product_packaging',
        ),
    ]
