# Generated by Django 3.2 on 2022-02-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0013_remove_bar_product_packaging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Cargo_pickup_license',
        ),
        migrations.RemoveField(
            model_name='account',
            name='International_license',
        ),
    ]
