# Generated by Django 3.2 on 2022-02-16 23:52

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0014_auto_20220216_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
