# Generated by Django 3.2 on 2022-02-17 01:15

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0015_alter_bar_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='publish',
        ),
        migrations.AddField(
            model_name='account',
            name='isSeeLastNotif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 2, 17)),
        ),
    ]
