# Generated by Django 3.2 on 2022-02-17 01:16

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0016_auto_20220217_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2022, 2, 17, 1, 16, 17, 644924, tzinfo=utc)),
        ),
    ]
