# Generated by Django 3.2 on 2022-02-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0019_notification_immortal'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lastOTP',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
