# Generated by Django 3.2 on 2022-02-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0020_account_lastotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lastOtpTimeSet',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
