# Generated by Django 3.2 on 2022-02-17 17:11

from django.db import migrations
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0023_alter_account_lastotptimeset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='lastOtpTimeSet',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=jdatetime.datetime.now),
        ),
    ]
