# Generated by Django 3.2 on 2022-02-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0030_alter_account_lastotptimeset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='lastOtpTimeSet',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
