# Generated by Django 3.2 on 2022-02-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbary_api', '0033_remove_account_lastotptimeset'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lastOtpTimeSet',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
